version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: source
    image: ollama/ollama:latest
    ports:
      - "11440:11434"
    volumes:
      - ollama_data:/root/.source
    restart: unless-stopped

  nats:
    image: nats:latest
    container_name: nats
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # Monitoring
    volumes:
      - nats_data:/data
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
  nats_data:
