version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: source
    image: ollama/ollama:latest
    ports:
      - "11440:11434" # REST API
    volumes:
      - ollama_data:/root/.source
    restart: unless-stopped

  nats:
    image: nats:latest
    container_name: nats
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # Monitoring
    volumes:
      - nats_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"      # MinIO API
      - "9001:9001"      # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
  nats_data:
  minio_data:
