version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caelus
    volumes:
      - ./relationalDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: source
    image: ollama/ollama:latest
    ports:
      - "11440:11434"
    volumes:
      - ollama_data:/root/.source
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
